version: "1.0"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "${BACKEND_PORT}:4000"
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build: ./frontend/
    ports:
      - "3000:3000"
    restart: always
    # depends_on defines what services that run first
    depends_on:
      - backend
